### ISSUE TITLE
PyPi package does not contain fixtures directory

### ISSUE THREAD

**Issue by duffn** [orcasgit/django-fitbit#22]
The 0.1.0 PyPi package does not contain the fixtures directory which causes Django 1.7 migrations to fail. Migration fitapp.0002_initial_data attempts to load data from fixtures/initial_data.json which is not there.

As a temporary workaround, download inital_data.json and place it in a fixtures directory wherever you installed django-fitbit.
https://github.com/orcasgit/django-fitbit/tree/master/fitapp/fixtures

**Comment by brad** [comment]
Thank you @duffn for pointing that out. Please use the new 0.1.1 version.
