### ISSUE TITLE
Feature request: Fitbit OAuth2 login

### ISSUE THREAD

**Issue by brad** [orcasgit/django-fitbit#24]

**Comment by Amar-Chaudhari** [comment]
Yes, we definitely need OAuth2 integration

**Comment by awidgery** [comment]
Fitbit OAuth 1 retirement is now set for Mar/Apr 2016:

https://dev.fitbit.com/docs/oauth2/

Is there any plan to support oauth2?

**Comment by brad** [comment]
Yes, we will absolutely support OAuth2 before the retirement date

**Comment by awidgery** [comment]
@brad great - thanks for this. Gives confidence to go ahead and use this library in anticipation!

**Comment by awidgery** [comment]
@brad is there any progress on this? Retirement of OAuth 1 is scheduled for 6 days' time...

**Comment by percyperez** [comment]
@awidgery The latest version of [django-fitbit](https://pypi.python.org/pypi/django-fitbit) `0.2.2` fully support OAuth2. We dropped [OAuth1](https://github.com/orcasgit/django-fitbit/blob/master/CHANGELOG.md#020-2016-03-23) support. Can we close this issue?

**Comment by awidgery** [comment]
@percyperez Yeah - I just saw that after I posted the message. Let's close the issue. Thanks
